### ISSUE TITLE
Make Ability-Triggering Items Configurable (with Support for Categories, NBT data and Item slot location)

### ISSUE THREAD

**Issue by taran2k** [taran2k/SprintStrikePlugin#2]
Make the item list that include the items one of which a player needs to hold in their main hand for the ability to work, configurable.
Items should be their lowercase full name, for example `diamond_pickaxe` or `stick`. A few exceptions:
- `pickaxe` should refer to all types of pickaxes;
- `sword` should refer to all types of swords;
- `axe` should refer to all types of axes;
- `shovel` should refer to all types of shovels;
- `hoe` should refer to all types of hoes;
- `helmet` should refer to all types of helmets;
- `chestplate` should refer to all types of chestplates;
- `leggings` should refer to all types of leggings;
- `boots` should refer to all types of boots;
- `shield` should refer to all types of shields;

Notwithstanding that all types of these items can also be added individually (but above listed would override those).

Also add support for where the item needs to be held (default: main hand).

Additionally, it would be even more desirable if the required items can be filtered by other properties like their custom name or other NBT data, like their enchantments, lore, etc. 
An example scenario: a server has a custom item which is a wooden_sword called the <Assassin's Dagger>, colour coded black, with an Unbreaking X enchantment and a custom enchantment (lore) called 'Killing Spree I'. Only this specific item should be allowed to perform the Sprint Strike ability at Tier 1. Likewise, for Tier 2 the exact same item only now with 'Killing Spree II' is the only item that is allowed to use the ability at Tier 2. 

**Example 1:**
```yml
tiers:
  tier_1:
    effects:
      - strength,2,2
      - speed,1,5
    combo_duration: 3
    max_teleport_distance: 5
    cooldown: 60
    damage_breaks_combo: true
    allowed_items:
      - wooden_sword
        custom_name: "&0Assassin's Dagger"
        enchantments:
          - unbreaking:10
        lore:
          - Killing Spree I
        slot: main_hand
```

**Example 2**
```yml
tiers:
  tier_1:
    effects:
      - strength,2,2
      - speed,1,5
    combo_duration: 3
    max_teleport_distance: 5
    cooldown: 60
    damage_breaks_combo: true
    allowed_items:
     - sword
     - netherite_axe
```
