### ISSUE TITLE
Add Tier-Configurable Water/Lava Support

### ISSUE THREAD

**Issue by taran2k** [taran2k/SprintStrikePlugin#5]
Create a new tier-based property that decides whether the ability can also be used in water/underwater and in lava. If not provided or wrongly provided, these properties should default to `false`.

**Example:**
```yaml
tier 1:
 # other properties...
 use_in_water: true
 use_in_lava: false
```
